//
// ExtraCurrencyAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ExtraCurrencyAPI {

    /**
     * enum for parameter xCapability
     */
    public enum XCapability_getExtraCurrencyInfo: String, CaseIterable {
        case subSecond = "sub-second"
    }

    /**

     - parameter id: (path) extra currency id 
     - parameter xCapability: (header) Request sub-second capability. (optional)
     - returns: EcPreview
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getExtraCurrencyInfo(id: Int, xCapability: XCapability_getExtraCurrencyInfo? = nil) async throws -> EcPreview {
        return try await getExtraCurrencyInfoWithRequestBuilder(id: id, xCapability: xCapability).execute().body
    }

    /**
     - GET /v2/extra-currency/{id}
     - Get extra currency info by id
     - parameter id: (path) extra currency id 
     - parameter xCapability: (header) Request sub-second capability. (optional)
     - returns: RequestBuilder<EcPreview> 
     */
    open class func getExtraCurrencyInfoWithRequestBuilder(id: Int, xCapability: XCapability_getExtraCurrencyInfo? = nil) -> RequestBuilder<EcPreview> {
        var localVariablePath = "/v2/extra-currency/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Capability": xCapability?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<EcPreview>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
