//
// LiteServerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class LiteServerAPI {

    /**
     * enum for parameter xCapability
     */
    public enum XCapability_getAllRawShardsInfo: String, CaseIterable {
        case subSecond = "sub-second"
    }

    /**

     - parameter blockId: (path) block ID: (workchain,shard,seqno,root_hash,file_hash) 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: GetAllRawShardsInfo200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getAllRawShardsInfo(blockId: String, xCapability: XCapability_getAllRawShardsInfo? = nil) async throws -> GetAllRawShardsInfo200Response {
        return try await getAllRawShardsInfoWithRequestBuilder(blockId: blockId, xCapability: xCapability).execute().body
    }

    /**
     - GET /v2/liteserver/get_all_shards_info/{block_id}
     - Get all raw shards info
     - parameter blockId: (path) block ID: (workchain,shard,seqno,root_hash,file_hash) 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: RequestBuilder<GetAllRawShardsInfo200Response> 
     */
    open class func getAllRawShardsInfoWithRequestBuilder(blockId: String, xCapability: XCapability_getAllRawShardsInfo? = nil) -> RequestBuilder<GetAllRawShardsInfo200Response> {
        var localVariablePath = "/v2/liteserver/get_all_shards_info/{block_id}"
        let blockIdPreEscape = "\(APIHelper.mapValueToPathItem(blockId))"
        let blockIdPostEscape = blockIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{block_id}", with: blockIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Capability": xCapability?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetAllRawShardsInfo200Response>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter xCapability
     */
    public enum XCapability_getOutMsgQueueSizes: String, CaseIterable {
        case subSecond = "sub-second"
    }

    /**

     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: GetOutMsgQueueSizes200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getOutMsgQueueSizes(xCapability: XCapability_getOutMsgQueueSizes? = nil) async throws -> GetOutMsgQueueSizes200Response {
        return try await getOutMsgQueueSizesWithRequestBuilder(xCapability: xCapability).execute().body
    }

    /**
     - GET /v2/liteserver/get_out_msg_queue_sizes
     - Get out msg queue sizes
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: RequestBuilder<GetOutMsgQueueSizes200Response> 
     */
    open class func getOutMsgQueueSizesWithRequestBuilder(xCapability: XCapability_getOutMsgQueueSizes? = nil) -> RequestBuilder<GetOutMsgQueueSizes200Response> {
        let localVariablePath = "/v2/liteserver/get_out_msg_queue_sizes"
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Capability": xCapability?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetOutMsgQueueSizes200Response>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter xCapability
     */
    public enum XCapability_getRawAccountState: String, CaseIterable {
        case subSecond = "sub-second"
    }

    /**

     - parameter accountId: (path) account ID 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - parameter targetBlock: (query) target block: (workchain,shard,seqno,root_hash,file_hash) (optional)
     - returns: GetRawAccountState200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRawAccountState(accountId: String, xCapability: XCapability_getRawAccountState? = nil, targetBlock: String? = nil) async throws -> GetRawAccountState200Response {
        return try await getRawAccountStateWithRequestBuilder(accountId: accountId, xCapability: xCapability, targetBlock: targetBlock).execute().body
    }

    /**
     - GET /v2/liteserver/get_account_state/{account_id}
     - Get raw account state
     - parameter accountId: (path) account ID 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - parameter targetBlock: (query) target block: (workchain,shard,seqno,root_hash,file_hash) (optional)
     - returns: RequestBuilder<GetRawAccountState200Response> 
     */
    open class func getRawAccountStateWithRequestBuilder(accountId: String, xCapability: XCapability_getRawAccountState? = nil, targetBlock: String? = nil) -> RequestBuilder<GetRawAccountState200Response> {
        var localVariablePath = "/v2/liteserver/get_account_state/{account_id}"
        let accountIdPreEscape = "\(APIHelper.mapValueToPathItem(accountId))"
        let accountIdPostEscape = accountIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{account_id}", with: accountIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "target_block": (wrappedValue: targetBlock?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Capability": xCapability?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetRawAccountState200Response>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter xCapability
     */
    public enum XCapability_getRawBlockProof: String, CaseIterable {
        case subSecond = "sub-second"
    }

    /**

     - parameter knownBlock: (query) known block: (workchain,shard,seqno,root_hash,file_hash) 
     - parameter mode: (query) mode 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - parameter targetBlock: (query) target block: (workchain,shard,seqno,root_hash,file_hash) (optional)
     - returns: GetRawBlockProof200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRawBlockProof(knownBlock: String, mode: Int, xCapability: XCapability_getRawBlockProof? = nil, targetBlock: String? = nil) async throws -> GetRawBlockProof200Response {
        return try await getRawBlockProofWithRequestBuilder(knownBlock: knownBlock, mode: mode, xCapability: xCapability, targetBlock: targetBlock).execute().body
    }

    /**
     - GET /v2/liteserver/get_block_proof
     - Get raw block proof
     - parameter knownBlock: (query) known block: (workchain,shard,seqno,root_hash,file_hash) 
     - parameter mode: (query) mode 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - parameter targetBlock: (query) target block: (workchain,shard,seqno,root_hash,file_hash) (optional)
     - returns: RequestBuilder<GetRawBlockProof200Response> 
     */
    open class func getRawBlockProofWithRequestBuilder(knownBlock: String, mode: Int, xCapability: XCapability_getRawBlockProof? = nil, targetBlock: String? = nil) -> RequestBuilder<GetRawBlockProof200Response> {
        let localVariablePath = "/v2/liteserver/get_block_proof"
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "known_block": (wrappedValue: knownBlock.encodeToJSON(), isExplode: true),
            "target_block": (wrappedValue: targetBlock?.encodeToJSON(), isExplode: true),
            "mode": (wrappedValue: mode.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Capability": xCapability?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetRawBlockProof200Response>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter xCapability
     */
    public enum XCapability_getRawBlockchainBlock: String, CaseIterable {
        case subSecond = "sub-second"
    }

    /**

     - parameter blockId: (path) block ID: (workchain,shard,seqno,root_hash,file_hash) 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: GetRawBlockchainBlock200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRawBlockchainBlock(blockId: String, xCapability: XCapability_getRawBlockchainBlock? = nil) async throws -> GetRawBlockchainBlock200Response {
        return try await getRawBlockchainBlockWithRequestBuilder(blockId: blockId, xCapability: xCapability).execute().body
    }

    /**
     - GET /v2/liteserver/get_block/{block_id}
     - Get raw blockchain block
     - parameter blockId: (path) block ID: (workchain,shard,seqno,root_hash,file_hash) 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: RequestBuilder<GetRawBlockchainBlock200Response> 
     */
    open class func getRawBlockchainBlockWithRequestBuilder(blockId: String, xCapability: XCapability_getRawBlockchainBlock? = nil) -> RequestBuilder<GetRawBlockchainBlock200Response> {
        var localVariablePath = "/v2/liteserver/get_block/{block_id}"
        let blockIdPreEscape = "\(APIHelper.mapValueToPathItem(blockId))"
        let blockIdPostEscape = blockIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{block_id}", with: blockIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Capability": xCapability?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetRawBlockchainBlock200Response>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter xCapability
     */
    public enum XCapability_getRawBlockchainBlockHeader: String, CaseIterable {
        case subSecond = "sub-second"
    }

    /**

     - parameter blockId: (path) block ID: (workchain,shard,seqno,root_hash,file_hash) 
     - parameter mode: (query) mode 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: GetRawBlockchainBlockHeader200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRawBlockchainBlockHeader(blockId: String, mode: Int, xCapability: XCapability_getRawBlockchainBlockHeader? = nil) async throws -> GetRawBlockchainBlockHeader200Response {
        return try await getRawBlockchainBlockHeaderWithRequestBuilder(blockId: blockId, mode: mode, xCapability: xCapability).execute().body
    }

    /**
     - GET /v2/liteserver/get_block_header/{block_id}
     - Get raw blockchain block header
     - parameter blockId: (path) block ID: (workchain,shard,seqno,root_hash,file_hash) 
     - parameter mode: (query) mode 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: RequestBuilder<GetRawBlockchainBlockHeader200Response> 
     */
    open class func getRawBlockchainBlockHeaderWithRequestBuilder(blockId: String, mode: Int, xCapability: XCapability_getRawBlockchainBlockHeader? = nil) -> RequestBuilder<GetRawBlockchainBlockHeader200Response> {
        var localVariablePath = "/v2/liteserver/get_block_header/{block_id}"
        let blockIdPreEscape = "\(APIHelper.mapValueToPathItem(blockId))"
        let blockIdPostEscape = blockIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{block_id}", with: blockIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "mode": (wrappedValue: mode.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Capability": xCapability?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetRawBlockchainBlockHeader200Response>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter xCapability
     */
    public enum XCapability_getRawBlockchainBlockState: String, CaseIterable {
        case subSecond = "sub-second"
    }

    /**

     - parameter blockId: (path) block ID: (workchain,shard,seqno,root_hash,file_hash) 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: GetRawBlockchainBlockState200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRawBlockchainBlockState(blockId: String, xCapability: XCapability_getRawBlockchainBlockState? = nil) async throws -> GetRawBlockchainBlockState200Response {
        return try await getRawBlockchainBlockStateWithRequestBuilder(blockId: blockId, xCapability: xCapability).execute().body
    }

    /**
     - GET /v2/liteserver/get_state/{block_id}
     - Get raw blockchain block state
     - parameter blockId: (path) block ID: (workchain,shard,seqno,root_hash,file_hash) 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: RequestBuilder<GetRawBlockchainBlockState200Response> 
     */
    open class func getRawBlockchainBlockStateWithRequestBuilder(blockId: String, xCapability: XCapability_getRawBlockchainBlockState? = nil) -> RequestBuilder<GetRawBlockchainBlockState200Response> {
        var localVariablePath = "/v2/liteserver/get_state/{block_id}"
        let blockIdPreEscape = "\(APIHelper.mapValueToPathItem(blockId))"
        let blockIdPostEscape = blockIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{block_id}", with: blockIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Capability": xCapability?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetRawBlockchainBlockState200Response>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter xCapability
     */
    public enum XCapability_getRawConfig: String, CaseIterable {
        case subSecond = "sub-second"
    }

    /**

     - parameter blockId: (path) block ID: (workchain,shard,seqno,root_hash,file_hash) 
     - parameter mode: (query) mode 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: GetRawConfig200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRawConfig(blockId: String, mode: Int, xCapability: XCapability_getRawConfig? = nil) async throws -> GetRawConfig200Response {
        return try await getRawConfigWithRequestBuilder(blockId: blockId, mode: mode, xCapability: xCapability).execute().body
    }

    /**
     - GET /v2/liteserver/get_config_all/{block_id}
     - Get raw config
     - parameter blockId: (path) block ID: (workchain,shard,seqno,root_hash,file_hash) 
     - parameter mode: (query) mode 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: RequestBuilder<GetRawConfig200Response> 
     */
    open class func getRawConfigWithRequestBuilder(blockId: String, mode: Int, xCapability: XCapability_getRawConfig? = nil) -> RequestBuilder<GetRawConfig200Response> {
        var localVariablePath = "/v2/liteserver/get_config_all/{block_id}"
        let blockIdPreEscape = "\(APIHelper.mapValueToPathItem(blockId))"
        let blockIdPostEscape = blockIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{block_id}", with: blockIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "mode": (wrappedValue: mode.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Capability": xCapability?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetRawConfig200Response>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter xCapability
     */
    public enum XCapability_getRawListBlockTransactions: String, CaseIterable {
        case subSecond = "sub-second"
    }

    /**

     - parameter blockId: (path) block ID: (workchain,shard,seqno,root_hash,file_hash) 
     - parameter mode: (query) mode 
     - parameter count: (query) count 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - parameter accountId: (query) account ID (optional)
     - parameter lt: (query) lt (optional)
     - returns: GetRawListBlockTransactions200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRawListBlockTransactions(blockId: String, mode: Int, count: Int, xCapability: XCapability_getRawListBlockTransactions? = nil, accountId: String? = nil, lt: Int64? = nil) async throws -> GetRawListBlockTransactions200Response {
        return try await getRawListBlockTransactionsWithRequestBuilder(blockId: blockId, mode: mode, count: count, xCapability: xCapability, accountId: accountId, lt: lt).execute().body
    }

    /**
     - GET /v2/liteserver/list_block_transactions/{block_id}
     - Get raw list block transactions
     - parameter blockId: (path) block ID: (workchain,shard,seqno,root_hash,file_hash) 
     - parameter mode: (query) mode 
     - parameter count: (query) count 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - parameter accountId: (query) account ID (optional)
     - parameter lt: (query) lt (optional)
     - returns: RequestBuilder<GetRawListBlockTransactions200Response> 
     */
    open class func getRawListBlockTransactionsWithRequestBuilder(blockId: String, mode: Int, count: Int, xCapability: XCapability_getRawListBlockTransactions? = nil, accountId: String? = nil, lt: Int64? = nil) -> RequestBuilder<GetRawListBlockTransactions200Response> {
        var localVariablePath = "/v2/liteserver/list_block_transactions/{block_id}"
        let blockIdPreEscape = "\(APIHelper.mapValueToPathItem(blockId))"
        let blockIdPostEscape = blockIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{block_id}", with: blockIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "mode": (wrappedValue: mode.encodeToJSON(), isExplode: true),
            "count": (wrappedValue: count.encodeToJSON(), isExplode: true),
            "account_id": (wrappedValue: accountId?.encodeToJSON(), isExplode: false),
            "lt": (wrappedValue: lt?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Capability": xCapability?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetRawListBlockTransactions200Response>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter xCapability
     */
    public enum XCapability_getRawMasterchainInfo: String, CaseIterable {
        case subSecond = "sub-second"
    }

    /**

     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: GetRawMasterchainInfo200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRawMasterchainInfo(xCapability: XCapability_getRawMasterchainInfo? = nil) async throws -> GetRawMasterchainInfo200Response {
        return try await getRawMasterchainInfoWithRequestBuilder(xCapability: xCapability).execute().body
    }

    /**
     - GET /v2/liteserver/get_masterchain_info
     - Get raw masterchain info
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: RequestBuilder<GetRawMasterchainInfo200Response> 
     */
    open class func getRawMasterchainInfoWithRequestBuilder(xCapability: XCapability_getRawMasterchainInfo? = nil) -> RequestBuilder<GetRawMasterchainInfo200Response> {
        let localVariablePath = "/v2/liteserver/get_masterchain_info"
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Capability": xCapability?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetRawMasterchainInfo200Response>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter xCapability
     */
    public enum XCapability_getRawMasterchainInfoExt: String, CaseIterable {
        case subSecond = "sub-second"
    }

    /**

     - parameter mode: (query) mode 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: GetRawMasterchainInfoExt200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRawMasterchainInfoExt(mode: Int, xCapability: XCapability_getRawMasterchainInfoExt? = nil) async throws -> GetRawMasterchainInfoExt200Response {
        return try await getRawMasterchainInfoExtWithRequestBuilder(mode: mode, xCapability: xCapability).execute().body
    }

    /**
     - GET /v2/liteserver/get_masterchain_info_ext
     - Get raw masterchain info ext
     - parameter mode: (query) mode 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: RequestBuilder<GetRawMasterchainInfoExt200Response> 
     */
    open class func getRawMasterchainInfoExtWithRequestBuilder(mode: Int, xCapability: XCapability_getRawMasterchainInfoExt? = nil) -> RequestBuilder<GetRawMasterchainInfoExt200Response> {
        let localVariablePath = "/v2/liteserver/get_masterchain_info_ext"
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "mode": (wrappedValue: mode.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Capability": xCapability?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetRawMasterchainInfoExt200Response>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter xCapability
     */
    public enum XCapability_getRawShardBlockProof: String, CaseIterable {
        case subSecond = "sub-second"
    }

    /**

     - parameter blockId: (path) block ID: (workchain,shard,seqno,root_hash,file_hash) 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: GetRawShardBlockProof200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRawShardBlockProof(blockId: String, xCapability: XCapability_getRawShardBlockProof? = nil) async throws -> GetRawShardBlockProof200Response {
        return try await getRawShardBlockProofWithRequestBuilder(blockId: blockId, xCapability: xCapability).execute().body
    }

    /**
     - GET /v2/liteserver/get_shard_block_proof/{block_id}
     - Get raw shard block proof
     - parameter blockId: (path) block ID: (workchain,shard,seqno,root_hash,file_hash) 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: RequestBuilder<GetRawShardBlockProof200Response> 
     */
    open class func getRawShardBlockProofWithRequestBuilder(blockId: String, xCapability: XCapability_getRawShardBlockProof? = nil) -> RequestBuilder<GetRawShardBlockProof200Response> {
        var localVariablePath = "/v2/liteserver/get_shard_block_proof/{block_id}"
        let blockIdPreEscape = "\(APIHelper.mapValueToPathItem(blockId))"
        let blockIdPostEscape = blockIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{block_id}", with: blockIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Capability": xCapability?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetRawShardBlockProof200Response>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter xCapability
     */
    public enum XCapability_getRawShardInfo: String, CaseIterable {
        case subSecond = "sub-second"
    }

    /**

     - parameter blockId: (path) block ID: (workchain,shard,seqno,root_hash,file_hash) 
     - parameter workchain: (query) workchain 
     - parameter shard: (query) shard 
     - parameter exact: (query) exact 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: GetRawShardInfo200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRawShardInfo(blockId: String, workchain: Int, shard: Int64, exact: Bool, xCapability: XCapability_getRawShardInfo? = nil) async throws -> GetRawShardInfo200Response {
        return try await getRawShardInfoWithRequestBuilder(blockId: blockId, workchain: workchain, shard: shard, exact: exact, xCapability: xCapability).execute().body
    }

    /**
     - GET /v2/liteserver/get_shard_info/{block_id}
     - Get raw shard info
     - parameter blockId: (path) block ID: (workchain,shard,seqno,root_hash,file_hash) 
     - parameter workchain: (query) workchain 
     - parameter shard: (query) shard 
     - parameter exact: (query) exact 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: RequestBuilder<GetRawShardInfo200Response> 
     */
    open class func getRawShardInfoWithRequestBuilder(blockId: String, workchain: Int, shard: Int64, exact: Bool, xCapability: XCapability_getRawShardInfo? = nil) -> RequestBuilder<GetRawShardInfo200Response> {
        var localVariablePath = "/v2/liteserver/get_shard_info/{block_id}"
        let blockIdPreEscape = "\(APIHelper.mapValueToPathItem(blockId))"
        let blockIdPostEscape = blockIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{block_id}", with: blockIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "workchain": (wrappedValue: workchain.encodeToJSON(), isExplode: true),
            "shard": (wrappedValue: shard.encodeToJSON(), isExplode: true),
            "exact": (wrappedValue: exact.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Capability": xCapability?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetRawShardInfo200Response>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter xCapability
     */
    public enum XCapability_getRawTime: String, CaseIterable {
        case subSecond = "sub-second"
    }

    /**

     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: GetRawTime200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRawTime(xCapability: XCapability_getRawTime? = nil) async throws -> GetRawTime200Response {
        return try await getRawTimeWithRequestBuilder(xCapability: xCapability).execute().body
    }

    /**
     - GET /v2/liteserver/get_time
     - Get raw time
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: RequestBuilder<GetRawTime200Response> 
     */
    open class func getRawTimeWithRequestBuilder(xCapability: XCapability_getRawTime? = nil) -> RequestBuilder<GetRawTime200Response> {
        let localVariablePath = "/v2/liteserver/get_time"
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Capability": xCapability?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetRawTime200Response>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter xCapability
     */
    public enum XCapability_getRawTransactions: String, CaseIterable {
        case subSecond = "sub-second"
    }

    /**

     - parameter accountId: (path) account ID 
     - parameter count: (query) count 
     - parameter lt: (query) lt 
     - parameter hash: (query) hash 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: GetRawTransactions200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRawTransactions(accountId: String, count: Int, lt: Int64, hash: String, xCapability: XCapability_getRawTransactions? = nil) async throws -> GetRawTransactions200Response {
        return try await getRawTransactionsWithRequestBuilder(accountId: accountId, count: count, lt: lt, hash: hash, xCapability: xCapability).execute().body
    }

    /**
     - GET /v2/liteserver/get_transactions/{account_id}
     - Get raw transactions
     - parameter accountId: (path) account ID 
     - parameter count: (query) count 
     - parameter lt: (query) lt 
     - parameter hash: (query) hash 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: RequestBuilder<GetRawTransactions200Response> 
     */
    open class func getRawTransactionsWithRequestBuilder(accountId: String, count: Int, lt: Int64, hash: String, xCapability: XCapability_getRawTransactions? = nil) -> RequestBuilder<GetRawTransactions200Response> {
        var localVariablePath = "/v2/liteserver/get_transactions/{account_id}"
        let accountIdPreEscape = "\(APIHelper.mapValueToPathItem(accountId))"
        let accountIdPostEscape = accountIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{account_id}", with: accountIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "count": (wrappedValue: count.encodeToJSON(), isExplode: true),
            "lt": (wrappedValue: lt.encodeToJSON(), isExplode: true),
            "hash": (wrappedValue: hash.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Capability": xCapability?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetRawTransactions200Response>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter xCapability
     */
    public enum XCapability_sendRawMessage: String, CaseIterable {
        case subSecond = "sub-second"
    }

    /**

     - parameter sendRawMessageRequest: (body) Data that is expected 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: SendRawMessage200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func sendRawMessage(sendRawMessageRequest: SendRawMessageRequest, xCapability: XCapability_sendRawMessage? = nil) async throws -> SendRawMessage200Response {
        return try await sendRawMessageWithRequestBuilder(sendRawMessageRequest: sendRawMessageRequest, xCapability: xCapability).execute().body
    }

    /**
     - POST /v2/liteserver/send_message
     - Send raw message to blockchain
     - parameter sendRawMessageRequest: (body) Data that is expected 
     - parameter xCapability: (header) Request sub-second capability. (optional, default to .subSecond)
     - returns: RequestBuilder<SendRawMessage200Response> 
     */
    open class func sendRawMessageWithRequestBuilder(sendRawMessageRequest: SendRawMessageRequest, xCapability: XCapability_sendRawMessage? = nil) -> RequestBuilder<SendRawMessage200Response> {
        let localVariablePath = "/v2/liteserver/send_message"
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: sendRawMessageRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
            "X-Capability": xCapability?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SendRawMessage200Response>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
