//
// MigrationAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class MigrationAPI {

    /**

     - parameter currencies: (query) accept gram and all possible fiat currencies, separated by commas (optional)
     - parameter getBlockchainRawAccountsRequest: (body) a list of account ids (optional)
     - returns: MigrationWallets
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getMigrationWallets(currencies: [String]? = nil, getBlockchainRawAccountsRequest: GetBlockchainRawAccountsRequest? = nil) async throws -> MigrationWallets {
        return try await getMigrationWalletsWithRequestBuilder(currencies: currencies, getBlockchainRawAccountsRequest: getBlockchainRawAccountsRequest).execute().body
    }

    /**
     - POST /v2/migration/wallets
     - Get migratable assets value (TON balance, jettons with prices, NFT count) for several wallets at once.
     - parameter currencies: (query) accept gram and all possible fiat currencies, separated by commas (optional)
     - parameter getBlockchainRawAccountsRequest: (body) a list of account ids (optional)
     - returns: RequestBuilder<MigrationWallets> 
     */
    open class func getMigrationWalletsWithRequestBuilder(currencies: [String]? = nil, getBlockchainRawAccountsRequest: GetBlockchainRawAccountsRequest? = nil) -> RequestBuilder<MigrationWallets> {
        let localVariablePath = "/v2/migration/wallets"
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: getBlockchainRawAccountsRequest)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "currencies": (wrappedValue: currencies?.encodeToJSON(), isExplode: false),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MigrationWallets>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**

     - parameter migrationPrepareRequest: (body)  
     - returns: MigrationPrepareResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func prepareMigration(migrationPrepareRequest: MigrationPrepareRequest) async throws -> MigrationPrepareResponse {
        return try await prepareMigrationWithRequestBuilder(migrationPrepareRequest: migrationPrepareRequest).execute().body
    }

    /**
     - POST /v2/migration/prepare
     - Prepare ordered signable transactions that migrate every asset from `from` to `to`.
     - parameter migrationPrepareRequest: (body)  
     - returns: RequestBuilder<MigrationPrepareResponse> 
     */
    open class func prepareMigrationWithRequestBuilder(migrationPrepareRequest: MigrationPrepareRequest) -> RequestBuilder<MigrationPrepareResponse> {
        let localVariablePath = "/v2/migration/prepare"
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: migrationPrepareRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MigrationPrepareResponse>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
