//
// RewardsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class RewardsAPI {

    /**
     Get current TON blockchain APY
     
     - returns: Double
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRewardsApy() async throws -> Double {
        return try await getRewardsApyWithRequestBuilder().execute().body
    }

    /**
     Get current TON blockchain APY
     - GET /v2/rewards/apy
     - Returns the current TON blockchain APY as a percent based on the latest completed validation round.
     - returns: RequestBuilder<Double> 
     */
    open class func getRewardsApyWithRequestBuilder() -> RequestBuilder<Double> {
        let localVariablePath = "/v2/rewards/apy"
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Double>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get historical APY and stake statistics
     
     - returns: RewardsStats
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRewardsStats() async throws -> RewardsStats {
        return try await getRewardsStatsWithRequestBuilder().execute().body
    }

    /**
     Get historical APY and stake statistics
     - GET /v2/rewards/stats
     - Returns time series of APY and total stake from past validation rounds.
     - returns: RequestBuilder<RewardsStats> 
     */
    open class func getRewardsStatsWithRequestBuilder() -> RequestBuilder<RewardsStats> {
        let localVariablePath = "/v2/rewards/stats"
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RewardsStats>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get per-validator reward distribution for a finished round
     
     - parameter electionId: (query) Election ID of the finished round. Mutually exclusive with &#x60;block&#x60; and &#x60;unixtime&#x60;.  (optional)
     - parameter block: (query) Masterchain block seqno within the finished round. Mutually exclusive with &#x60;election_id&#x60; and &#x60;unixtime&#x60;.  (optional)
     - parameter unixtime: (query) Unix timestamp (seconds). Looks up the masterchain block at this time and uses it as the anchor. Mutually exclusive with &#x60;election_id&#x60; and &#x60;block&#x60;.  (optional)
     - parameter shallow: (query) Set to &#x60;1&#x60; to return only basic validator info (rank, pubkey, effective_stake, weight, reward, pool). Skips pool type detection, owner/validator addresses, nominator data, and returned-stake lookup — significantly faster.  (optional, default to false)
     - returns: RoundRewardsResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRoundRewards(electionId: Int64? = nil, block: Int? = nil, unixtime: Int? = nil, shallow: Bool? = nil) async throws -> RoundRewardsResponse {
        return try await getRoundRewardsWithRequestBuilder(electionId: electionId, block: block, unixtime: unixtime, shallow: shallow).execute().body
    }

    /**
     Get per-validator reward distribution for a finished round
     - GET /v2/rewards/round-rewards
     - Computes per-validator and per-nominator reward distribution for a finished validation round using the elector's bonuses value. 
     - parameter electionId: (query) Election ID of the finished round. Mutually exclusive with &#x60;block&#x60; and &#x60;unixtime&#x60;.  (optional)
     - parameter block: (query) Masterchain block seqno within the finished round. Mutually exclusive with &#x60;election_id&#x60; and &#x60;unixtime&#x60;.  (optional)
     - parameter unixtime: (query) Unix timestamp (seconds). Looks up the masterchain block at this time and uses it as the anchor. Mutually exclusive with &#x60;election_id&#x60; and &#x60;block&#x60;.  (optional)
     - parameter shallow: (query) Set to &#x60;1&#x60; to return only basic validator info (rank, pubkey, effective_stake, weight, reward, pool). Skips pool type detection, owner/validator addresses, nominator data, and returned-stake lookup — significantly faster.  (optional, default to false)
     - returns: RequestBuilder<RoundRewardsResponse> 
     */
    open class func getRoundRewardsWithRequestBuilder(electionId: Int64? = nil, block: Int? = nil, unixtime: Int? = nil, shallow: Bool? = nil) -> RequestBuilder<RoundRewardsResponse> {
        let localVariablePath = "/v2/rewards/round-rewards"
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "election_id": (wrappedValue: electionId?.encodeToJSON(), isExplode: true),
            "block": (wrappedValue: block?.encodeToJSON(), isExplode: true),
            "unixtime": (wrappedValue: unixtime?.encodeToJSON(), isExplode: true),
            "shallow": (wrappedValue: shallow?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RoundRewardsResponse>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get validation round metadata
     
     - parameter electionId: (query) Return the single round matching this election ID. Mutually exclusive with &#x60;block&#x60; and &#x60;unixtime&#x60;.  (optional)
     - parameter block: (query) Find the round containing this masterchain block seqno and return it plus up to &#x60;limit-1&#x60; older rounds. Mutually exclusive with &#x60;election_id&#x60; and &#x60;unixtime&#x60;.  (optional)
     - parameter unixtime: (query) Unix timestamp (seconds). Looks up the masterchain block at this time and uses it as the anchor. Mutually exclusive with &#x60;election_id&#x60; and &#x60;block&#x60;.  (optional)
     - returns: ValidationRoundsResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getValidationRounds(electionId: Int64? = nil, block: Int? = nil, unixtime: Int? = nil) async throws -> ValidationRoundsResponse {
        return try await getValidationRoundsWithRequestBuilder(electionId: electionId, block: block, unixtime: unixtime).execute().body
    }

    /**
     Get validation round metadata
     - GET /v2/rewards/validation-rounds
     - Returns past and current validation rounds with boundaries, stakes, and bonuses. Always uses the latest masterchain block. 
     - parameter electionId: (query) Return the single round matching this election ID. Mutually exclusive with &#x60;block&#x60; and &#x60;unixtime&#x60;.  (optional)
     - parameter block: (query) Find the round containing this masterchain block seqno and return it plus up to &#x60;limit-1&#x60; older rounds. Mutually exclusive with &#x60;election_id&#x60; and &#x60;unixtime&#x60;.  (optional)
     - parameter unixtime: (query) Unix timestamp (seconds). Looks up the masterchain block at this time and uses it as the anchor. Mutually exclusive with &#x60;election_id&#x60; and &#x60;block&#x60;.  (optional)
     - returns: RequestBuilder<ValidationRoundsResponse> 
     */
    open class func getValidationRoundsWithRequestBuilder(electionId: Int64? = nil, block: Int? = nil, unixtime: Int? = nil) -> RequestBuilder<ValidationRoundsResponse> {
        let localVariablePath = "/v2/rewards/validation-rounds"
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "election_id": (wrappedValue: electionId?.encodeToJSON(), isExplode: true),
            "block": (wrappedValue: block?.encodeToJSON(), isExplode: true),
            "unixtime": (wrappedValue: unixtime?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ValidationRoundsResponse>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get all current validators
     
     - parameter seqno: (query) Masterchain block seqno. Defaults to latest. Mutually exclusive with &#x60;unixtime&#x60;.  (optional)
     - parameter unixtime: (query) Unix timestamp (seconds). Looks up the masterchain block at this time and uses it as the anchor. Mutually exclusive with &#x60;seqno&#x60;.  (optional)
     - parameter shallow: (query) Set to &#x60;1&#x60; to return only basic validator info (rank, pubkey, effective_stake, weight, reward, pool). Skips pool type detection, owner/validator addresses, nominator data, and returned-stake lookup — significantly faster.  (optional, default to false)
     - returns: ValidatorsResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getValidators(seqno: Int? = nil, unixtime: Int? = nil, shallow: Bool? = nil) async throws -> ValidatorsResponse {
        return try await getValidatorsWithRequestBuilder(seqno: seqno, unixtime: unixtime, shallow: shallow).execute().body
    }

    /**
     Get all current validators
     - GET /v2/rewards/validators
     - Returns all current validators with stakes, rewards, pool addresses, and (optionally) nominator breakdowns. 
     - parameter seqno: (query) Masterchain block seqno. Defaults to latest. Mutually exclusive with &#x60;unixtime&#x60;.  (optional)
     - parameter unixtime: (query) Unix timestamp (seconds). Looks up the masterchain block at this time and uses it as the anchor. Mutually exclusive with &#x60;seqno&#x60;.  (optional)
     - parameter shallow: (query) Set to &#x60;1&#x60; to return only basic validator info (rank, pubkey, effective_stake, weight, reward, pool). Skips pool type detection, owner/validator addresses, nominator data, and returned-stake lookup — significantly faster.  (optional, default to false)
     - returns: RequestBuilder<ValidatorsResponse> 
     */
    open class func getValidatorsWithRequestBuilder(seqno: Int? = nil, unixtime: Int? = nil, shallow: Bool? = nil) -> RequestBuilder<ValidatorsResponse> {
        let localVariablePath = "/v2/rewards/validators"
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "seqno": (wrappedValue: seqno?.encodeToJSON(), isExplode: true),
            "unixtime": (wrappedValue: unixtime?.encodeToJSON(), isExplode: true),
            "shallow": (wrappedValue: shallow?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ValidatorsResponse>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
