//
// UtilitiesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class UtilitiesAPI {

    /**
     * enum for parameter xCapability
     */
    public enum XCapability_addressParse: String, CaseIterable {
        case subSecond = "sub-second"
    }

    /**

     - parameter accountId: (path) account ID 
     - parameter xCapability: (header) Request sub-second capability. (optional)
     - returns: AddressParse200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func addressParse(accountId: String, xCapability: XCapability_addressParse? = nil) async throws -> AddressParse200Response {
        return try await addressParseWithRequestBuilder(accountId: accountId, xCapability: xCapability).execute().body
    }

    /**
     - GET /v2/address/{account_id}/parse
     - parse address and display in all formats
     - parameter accountId: (path) account ID 
     - parameter xCapability: (header) Request sub-second capability. (optional)
     - returns: RequestBuilder<AddressParse200Response> 
     */
    open class func addressParseWithRequestBuilder(accountId: String, xCapability: XCapability_addressParse? = nil) -> RequestBuilder<AddressParse200Response> {
        var localVariablePath = "/v2/address/{account_id}/parse"
        let accountIdPreEscape = "\(APIHelper.mapValueToPathItem(accountId))"
        let accountIdPostEscape = accountIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{account_id}", with: accountIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Capability": xCapability?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AddressParse200Response>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter xCapability
     */
    public enum XCapability_getOpenapiJson: String, CaseIterable {
        case subSecond = "sub-second"
    }

    /**

     - parameter xCapability: (header) Request sub-second capability. (optional)
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getOpenapiJson(xCapability: XCapability_getOpenapiJson? = nil) async throws -> AnyCodable {
        return try await getOpenapiJsonWithRequestBuilder(xCapability: xCapability).execute().body
    }

    /**
     - GET /v2/openapi.json
     - Get the openapi.json file
     - parameter xCapability: (header) Request sub-second capability. (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func getOpenapiJsonWithRequestBuilder(xCapability: XCapability_getOpenapiJson? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/v2/openapi.json"
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Capability": xCapability?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter xCapability
     */
    public enum XCapability_getOpenapiYml: String, CaseIterable {
        case subSecond = "sub-second"
    }

    /**

     - parameter xCapability: (header) Request sub-second capability. (optional)
     - returns: URL
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getOpenapiYml(xCapability: XCapability_getOpenapiYml? = nil) async throws -> URL {
        return try await getOpenapiYmlWithRequestBuilder(xCapability: xCapability).execute().body
    }

    /**
     - GET /v2/openapi.yml
     - Get the openapi.yml file
     - parameter xCapability: (header) Request sub-second capability. (optional)
     - returns: RequestBuilder<URL> 
     */
    open class func getOpenapiYmlWithRequestBuilder(xCapability: XCapability_getOpenapiYml? = nil) -> RequestBuilder<URL> {
        let localVariablePath = "/v2/openapi.yml"
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Capability": xCapability?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<URL>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     * enum for parameter xCapability
     */
    public enum XCapability_status: String, CaseIterable {
        case subSecond = "sub-second"
    }

    /**

     - parameter xCapability: (header) Request sub-second capability. (optional)
     - returns: ServiceStatus
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func status(xCapability: XCapability_status? = nil) async throws -> ServiceStatus {
        return try await statusWithRequestBuilder(xCapability: xCapability).execute().body
    }

    /**
     - GET /v2/status
     - Status
     - parameter xCapability: (header) Request sub-second capability. (optional)
     - returns: RequestBuilder<ServiceStatus> 
     */
    open class func statusWithRequestBuilder(xCapability: XCapability_status? = nil) -> RequestBuilder<ServiceStatus> {
        let localVariablePath = "/v2/status"
        let localVariableURLString = TonAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "X-Capability": xCapability?.encodeToJSON(),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ServiceStatus>.Type = TonAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
