//
// AccountStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum AccountStatus: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case nonexist = "nonexist"
    case uninit = "uninit"
    case active = "active"
    case frozen = "frozen"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
