//
// AccountEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** High-level view over a transaction trace caused by a single inbound message. TonAPI analyses the trace, detects known patterns and groups low-level transactions into user-facing actions (Jetton transfer, NFT purchase, etc.). Actions are a best-effort UI abstraction and may change; do not rely on them for protocol-critical logic.  */
public struct AccountEvent: Codable, JSONEncodable, Hashable {

    public var eventId: String
    public var account: AccountAddress
    public var timestamp: Int64
    public var actions: [Action]
    /** scam */
    public var isScam: Bool
    public var lt: Int64
    /** Event trace is not finished yet. Transactions still happening. */
    public var inProgress: Bool
    /** Net TON change for this account not explained by actions, in nanotons: extra = final_balance - initial_balance - sum(explicit TON changes from actions). extra < 0 - implicit fee, extra > 0 - refund. For UI display only  */
    public var extra: Int64
    /** Event completion ratio in [0,1] */
    public var progress: Float
    /** Normalized hash of the root external inbound message (hex). */
    public var extMsgHash: String?

    public init(eventId: String, account: AccountAddress, timestamp: Int64, actions: [Action], isScam: Bool, lt: Int64, inProgress: Bool, extra: Int64, progress: Float, extMsgHash: String? = nil) {
        self.eventId = eventId
        self.account = account
        self.timestamp = timestamp
        self.actions = actions
        self.isScam = isScam
        self.lt = lt
        self.inProgress = inProgress
        self.extra = extra
        self.progress = progress
        self.extMsgHash = extMsgHash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventId = "event_id"
        case account
        case timestamp
        case actions
        case isScam = "is_scam"
        case lt
        case inProgress = "in_progress"
        case extra
        case progress
        case extMsgHash = "ext_msg_hash"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eventId, forKey: .eventId)
        try container.encode(account, forKey: .account)
        try container.encode(timestamp, forKey: .timestamp)
        try container.encode(actions, forKey: .actions)
        try container.encode(isScam, forKey: .isScam)
        try container.encode(lt, forKey: .lt)
        try container.encode(inProgress, forKey: .inProgress)
        try container.encode(extra, forKey: .extra)
        try container.encode(progress, forKey: .progress)
        try container.encodeIfPresent(extMsgHash, forKey: .extMsgHash)
    }
}

