//
// AccountStakingInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AccountStakingInfo: Codable, JSONEncodable, Hashable {

    public var pool: String
    public var amount: Int64
    public var pendingDeposit: Int64
    public var pendingWithdraw: Int64
    public var readyWithdraw: Int64

    public init(pool: String, amount: Int64, pendingDeposit: Int64, pendingWithdraw: Int64, readyWithdraw: Int64) {
        self.pool = pool
        self.amount = amount
        self.pendingDeposit = pendingDeposit
        self.pendingWithdraw = pendingWithdraw
        self.readyWithdraw = readyWithdraw
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pool
        case amount
        case pendingDeposit = "pending_deposit"
        case pendingWithdraw = "pending_withdraw"
        case readyWithdraw = "ready_withdraw"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pool, forKey: .pool)
        try container.encode(amount, forKey: .amount)
        try container.encode(pendingDeposit, forKey: .pendingDeposit)
        try container.encode(pendingWithdraw, forKey: .pendingWithdraw)
        try container.encode(readyWithdraw, forKey: .readyWithdraw)
    }
}

