//
// ActionSimplePreview.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** shortly describes what this action is about. */
public struct ActionSimplePreview: Codable, JSONEncodable, Hashable {

    public var name: String
    public var description: String
    /** a link to an image for this particular action. */
    public var actionImage: String?
    public var value: String?
    /** a link to an image that depicts this action's asset. */
    public var valueImage: String?
    public var accounts: [AccountAddress]

    public init(name: String, description: String, actionImage: String? = nil, value: String? = nil, valueImage: String? = nil, accounts: [AccountAddress]) {
        self.name = name
        self.description = description
        self.actionImage = actionImage
        self.value = value
        self.valueImage = valueImage
        self.accounts = accounts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case actionImage = "action_image"
        case value
        case valueImage = "value_image"
        case accounts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(description, forKey: .description)
        try container.encodeIfPresent(actionImage, forKey: .actionImage)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encodeIfPresent(valueImage, forKey: .valueImage)
        try container.encode(accounts, forKey: .accounts)
    }
}

