//
// ApyHistory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApyHistory: Codable, JSONEncodable, Hashable {

    public var apy: Double
    public var time: Int

    public init(apy: Double, time: Int) {
        self.apy = apy
        self.time = time
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case apy
        case time
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(apy, forKey: .apy)
        try container.encode(time, forKey: .time)
    }
}

