//
// BlockchainConfig40.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The configuration for punishment for improper behavior (non-validation). In the absence of the parameter, the default fine size is 101 TON */
public struct BlockchainConfig40: Codable, JSONEncodable, Hashable {

    public var misbehaviourPunishmentConfig: MisbehaviourPunishmentConfig

    public init(misbehaviourPunishmentConfig: MisbehaviourPunishmentConfig) {
        self.misbehaviourPunishmentConfig = misbehaviourPunishmentConfig
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case misbehaviourPunishmentConfig = "misbehaviour_punishment_config"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(misbehaviourPunishmentConfig, forKey: .misbehaviourPunishmentConfig)
    }
}

