//
// BlockchainConfig24.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The cost of sending messages in the masterchain of the TON blockchain. */
public struct BlockchainConfig24: Codable, JSONEncodable, Hashable {

    public var msgForwardPrices: MsgForwardPrices

    public init(msgForwardPrices: MsgForwardPrices) {
        self.msgForwardPrices = msgForwardPrices
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case msgForwardPrices = "msg_forward_prices"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(msgForwardPrices, forKey: .msgForwardPrices)
    }
}

