//
// BlockchainConfig11.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** This parameter indicates under what conditions proposals to change the TON configuration are accepted. */
public struct BlockchainConfig11: Codable, JSONEncodable, Hashable {

    public var normalParams: ConfigProposalSetup
    public var criticalParams: ConfigProposalSetup

    public init(normalParams: ConfigProposalSetup, criticalParams: ConfigProposalSetup) {
        self.normalParams = normalParams
        self.criticalParams = criticalParams
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case normalParams = "normal_params"
        case criticalParams = "critical_params"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(normalParams, forKey: .normalParams)
        try container.encode(criticalParams, forKey: .criticalParams)
    }
}

