//
// BlockInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BlockInfo: Codable, JSONEncodable, Hashable {

    /** Masterchain block sequence number. */
    public var seqno: Int
    public var utime: Int64?

    public init(seqno: Int, utime: Int64? = nil) {
        self.seqno = seqno
        self.utime = utime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case seqno
        case utime
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(seqno, forKey: .seqno)
        try container.encodeIfPresent(utime, forKey: .utime)
    }
}

