//
// BlockchainConfig79.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Bridge parameters for wrapping tokens from other networks into tokens on the TON network. */
public struct BlockchainConfig79: Codable, JSONEncodable, Hashable {

    public var jettonBridgeParams: JettonBridgeParams

    public init(jettonBridgeParams: JettonBridgeParams) {
        self.jettonBridgeParams = jettonBridgeParams
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case jettonBridgeParams = "jetton_bridge_params"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(jettonBridgeParams, forKey: .jettonBridgeParams)
    }
}

