//
// BlockchainConfig30.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The configuration for the new consensus protocol. Each chain can have its own optional configuration. */
public struct BlockchainConfig30: Codable, JSONEncodable, Hashable {

    public var mc: NewConsensusConfig?
    public var shard: NewConsensusConfig?

    public init(mc: NewConsensusConfig? = nil, shard: NewConsensusConfig? = nil) {
        self.mc = mc
        self.shard = shard
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mc
        case shard
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(mc, forKey: .mc)
        try container.encodeIfPresent(shard, forKey: .shard)
    }
}

