//
// BlockchainConfig9.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** List of mandatory parameters of the blockchain config. */
public struct BlockchainConfig9: Codable, JSONEncodable, Hashable {

    public var mandatoryParams: [Int]

    public init(mandatoryParams: [Int]) {
        self.mandatoryParams = mandatoryParams
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mandatoryParams = "mandatory_params"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(mandatoryParams, forKey: .mandatoryParams)
    }
}

