//
// BlockchainRawAccounts.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BlockchainRawAccounts: Codable, JSONEncodable, Hashable {

    public var accounts: [BlockchainRawAccount]

    public init(accounts: [BlockchainRawAccount]) {
        self.accounts = accounts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accounts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accounts, forKey: .accounts)
    }
}

