//
// BlockchainConfig71.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Bridge parameters for wrapping TON in other networks. */
public struct BlockchainConfig71: Codable, JSONEncodable, Hashable {

    public var oracleBridgeParams: OracleBridgeParams

    public init(oracleBridgeParams: OracleBridgeParams) {
        self.oracleBridgeParams = oracleBridgeParams
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case oracleBridgeParams = "oracle_bridge_params"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(oracleBridgeParams, forKey: .oracleBridgeParams)
    }
}

