//
// BlockchainConfig12.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Workchains in the TON Blockchain */
public struct BlockchainConfig12: Codable, JSONEncodable, Hashable {

    public var workchains: [WorkchainDescr]

    public init(workchains: [WorkchainDescr]) {
        self.workchains = workchains
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case workchains
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(workchains, forKey: .workchains)
    }
}

