//
// ChartPoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChartPoint: Codable, JSONEncodable, Hashable {

    /** Unix timestamp of the data point */
    public var timestamp: Int64
    /** Decimal price of the token in the requested currency */
    public var value: Double

    public init(timestamp: Int64, value: Double) {
        self.timestamp = timestamp
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case timestamp
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(timestamp, forKey: .timestamp)
        try container.encode(value, forKey: .value)
    }
}

