//
// ChartPointsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChartPointsInner: Codable, JSONEncodable, Hashable {

    /** Unix timestamp of the data point */
    public var timestamp: Int64
    /** Decimal price of the token in the requested currency */
    public var price: Double

    public init(timestamp: Int64, price: Double) {
        self.timestamp = timestamp
        self.price = price
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case timestamp
        case price
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(timestamp, forKey: .timestamp)
        try container.encode(price, forKey: .price)
    }
}

