//
// ComputeSkipReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ComputeSkipReason: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case noState = "cskip_no_state"
    case badState = "cskip_bad_state"
    case noGas = "cskip_no_gas"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
