//
// ComputeSkipReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ComputeSkipReason: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case cskipNoState = "cskip_no_state"
    case cskipBadState = "cskip_bad_state"
    case cskipNoGas = "cskip_no_gas"
    case cskipSuspended = "cskip_suspended"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
