//
// ContractDeployAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ContractDeployAction: Codable, JSONEncodable, Hashable {

    public var address: String
    public var interfaces: [String]

    public init(address: String, interfaces: [String]) {
        self.address = address
        self.interfaces = interfaces
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case interfaces
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encode(interfaces, forKey: .interfaces)
    }
}

