//
// DecodedMessageExtInMsgDecodedWalletHighloadV2.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DecodedMessageExtInMsgDecodedWalletHighloadV2: Codable, JSONEncodable, Hashable {

    public var subwalletId: Int64
    public var boundedQueryId: String
    public var rawMessages: [DecodedRawMessage]

    public init(subwalletId: Int64, boundedQueryId: String, rawMessages: [DecodedRawMessage]) {
        self.subwalletId = subwalletId
        self.boundedQueryId = boundedQueryId
        self.rawMessages = rawMessages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case subwalletId = "subwallet_id"
        case boundedQueryId = "bounded_query_id"
        case rawMessages = "raw_messages"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(subwalletId, forKey: .subwalletId)
        try container.encode(boundedQueryId, forKey: .boundedQueryId)
        try container.encode(rawMessages, forKey: .rawMessages)
    }
}

