//
// DomainRenewAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DomainRenewAction: Codable, JSONEncodable, Hashable {

    public var domain: String
    public var contractAddress: String
    public var renewer: AccountAddress

    public init(domain: String, contractAddress: String, renewer: AccountAddress) {
        self.domain = domain
        self.contractAddress = contractAddress
        self.renewer = renewer
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case domain
        case contractAddress = "contract_address"
        case renewer
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(domain, forKey: .domain)
        try container.encode(contractAddress, forKey: .contractAddress)
        try container.encode(renewer, forKey: .renewer)
    }
}

