//
// DomainBid.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DomainBid: Codable, JSONEncodable, Hashable {

    public var success: Bool = false
    public var value: Int64
    public var txTime: Int64
    public var txHash: String
    public var bidder: AccountAddress

    public init(success: Bool = false, value: Int64, txTime: Int64, txHash: String, bidder: AccountAddress) {
        self.success = success
        self.value = value
        self.txTime = txTime
        self.txHash = txHash
        self.bidder = bidder
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case value
        case txTime
        case txHash
        case bidder
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(value, forKey: .value)
        try container.encode(txTime, forKey: .txTime)
        try container.encode(txHash, forKey: .txHash)
        try container.encode(bidder, forKey: .bidder)
    }
}

