//
// Event.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Event: Codable, JSONEncodable, Hashable {

    public var eventId: String
    public var timestamp: Int64
    public var actions: [Action]
    public var valueFlow: [ValueFlow]
    /** scam */
    public var isScam: Bool
    public var lt: Int64
    /** Event trace is not finished yet. Transactions still happening. */
    public var inProgress: Bool
    public var progress: Float
    /** ID of the slice where this event was finalized. Null if not yet finalized. */
    public var lastSliceId: Int64?
    /** Normalized hash of the root external inbound message (hex). */
    public var extMsgHash: String?

    public init(eventId: String, timestamp: Int64, actions: [Action], valueFlow: [ValueFlow], isScam: Bool, lt: Int64, inProgress: Bool, progress: Float, lastSliceId: Int64? = nil, extMsgHash: String? = nil) {
        self.eventId = eventId
        self.timestamp = timestamp
        self.actions = actions
        self.valueFlow = valueFlow
        self.isScam = isScam
        self.lt = lt
        self.inProgress = inProgress
        self.progress = progress
        self.lastSliceId = lastSliceId
        self.extMsgHash = extMsgHash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventId = "event_id"
        case timestamp
        case actions
        case valueFlow = "value_flow"
        case isScam = "is_scam"
        case lt
        case inProgress = "in_progress"
        case progress
        case lastSliceId = "last_slice_id"
        case extMsgHash = "ext_msg_hash"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eventId, forKey: .eventId)
        try container.encode(timestamp, forKey: .timestamp)
        try container.encode(actions, forKey: .actions)
        try container.encode(valueFlow, forKey: .valueFlow)
        try container.encode(isScam, forKey: .isScam)
        try container.encode(lt, forKey: .lt)
        try container.encode(inProgress, forKey: .inProgress)
        try container.encode(progress, forKey: .progress)
        try container.encodeIfPresent(lastSliceId, forKey: .lastSliceId)
        try container.encodeIfPresent(extMsgHash, forKey: .extMsgHash)
    }
}

