//
// ExecGetMethodWithBodyForBlockchainAccountRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ExecGetMethodWithBodyForBlockchainAccountRequest: Codable, JSONEncodable, Hashable {

    public var args: [ExecGetMethodArg]

    public init(args: [ExecGetMethodArg]) {
        self.args = args
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case args
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(args, forKey: .args)
    }
}

