//
// GaslessTx.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GaslessTx: Codable, JSONEncodable, Hashable {

    public var protocolName: String

    public init(protocolName: String) {
        self.protocolName = protocolName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case protocolName = "protocol_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(protocolName, forKey: .protocolName)
    }
}

