//
// GaslessEstimateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GaslessEstimateRequest: Codable, JSONEncodable, Hashable {

    public var walletAddress: String
    public var walletPublicKey: String
    public var messages: [DecodeMessageRequest]

    public init(walletAddress: String, walletPublicKey: String, messages: [DecodeMessageRequest]) {
        self.walletAddress = walletAddress
        self.walletPublicKey = walletPublicKey
        self.messages = messages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case walletAddress = "wallet_address"
        case walletPublicKey = "wallet_public_key"
        case messages
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(walletAddress, forKey: .walletAddress)
        try container.encode(walletPublicKey, forKey: .walletPublicKey)
        try container.encode(messages, forKey: .messages)
    }
}

