//
// GaslessConfigGasJettonsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GaslessConfigGasJettonsInner: Codable, JSONEncodable, Hashable {

    public var masterId: String

    public init(masterId: String) {
        self.masterId = masterId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case masterId = "master_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(masterId, forKey: .masterId)
    }
}

