//
// GetAccountDiff200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetAccountDiff200Response: Codable, JSONEncodable, Hashable {

    public var balanceChange: Int64

    public init(balanceChange: Int64) {
        self.balanceChange = balanceChange
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case balanceChange = "balance_change"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(balanceChange, forKey: .balanceChange)
    }
}

