//
// GetInscriptionOpTemplate200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetInscriptionOpTemplate200Response: Codable, JSONEncodable, Hashable {

    public var comment: String
    public var destination: String

    public init(comment: String, destination: String) {
        self.comment = comment
        self.destination = destination
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case comment
        case destination
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(comment, forKey: .comment)
        try container.encode(destination, forKey: .destination)
    }
}

