//
// GetOpenapiJsonDefaultResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetOpenapiJsonDefaultResponse: Codable, JSONEncodable, Hashable {

    public var error: String
    public var errorCode: Int64?

    public init(error: String, errorCode: Int64? = nil) {
        self.error = error
        self.errorCode = errorCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case error
        case errorCode = "error_code"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(error, forKey: .error)
        try container.encodeIfPresent(errorCode, forKey: .errorCode)
    }
}

