//
// GetOutMsgQueueSizes200ResponseShardsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetOutMsgQueueSizes200ResponseShardsInner: Codable, JSONEncodable, Hashable {

    public var id: BlockRaw
    public var size: Int

    public init(id: BlockRaw, size: Int) {
        self.id = id
        self.size = size
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case size
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(size, forKey: .size)
    }
}

