//
// GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForwardSignatures.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForwardSignatures: Codable, JSONEncodable, Hashable {

    public var validatorSetHash: Int64
    public var catchainSeqno: Int
    public var signatures: [GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForwardSignaturesSignaturesInner]

    public init(validatorSetHash: Int64, catchainSeqno: Int, signatures: [GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkForwardSignaturesSignaturesInner]) {
        self.validatorSetHash = validatorSetHash
        self.catchainSeqno = catchainSeqno
        self.signatures = signatures
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case validatorSetHash = "validator_set_hash"
        case catchainSeqno = "catchain_seqno"
        case signatures
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(validatorSetHash, forKey: .validatorSetHash)
        try container.encode(catchainSeqno, forKey: .catchainSeqno)
        try container.encode(signatures, forKey: .signatures)
    }
}

