//
// GetRawMasterchainInfo200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetRawMasterchainInfo200Response: Codable, JSONEncodable, Hashable {

    public var last: BlockRaw
    public var stateRootHash: String
    public var _init: InitStateRaw

    public init(last: BlockRaw, stateRootHash: String, _init: InitStateRaw) {
        self.last = last
        self.stateRootHash = stateRootHash
        self._init = _init
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case last
        case stateRootHash = "state_root_hash"
        case _init = "init"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(last, forKey: .last)
        try container.encode(stateRootHash, forKey: .stateRootHash)
        try container.encode(_init, forKey: ._init)
    }
}

