//
// GetRawListBlockTransactions200ResponseIdsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetRawListBlockTransactions200ResponseIdsInner: Codable, JSONEncodable, Hashable {

    public var mode: Int
    public var account: String?
    public var lt: Int64?
    public var hash: String?

    public init(mode: Int, account: String? = nil, lt: Int64? = nil, hash: String? = nil) {
        self.mode = mode
        self.account = account
        self.lt = lt
        self.hash = hash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mode
        case account
        case lt
        case hash
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(mode, forKey: .mode)
        try container.encodeIfPresent(account, forKey: .account)
        try container.encodeIfPresent(lt, forKey: .lt)
        try container.encodeIfPresent(hash, forKey: .hash)
    }
}

