//
// GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkBack.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetRawBlockProof200ResponseStepsInnerLiteServerBlockLinkBack: Codable, JSONEncodable, Hashable {

    public var toKeyBlock: Bool
    public var from: BlockRaw
    public var to: BlockRaw
    public var destProof: String
    public var proof: String
    public var stateProof: String

    public init(toKeyBlock: Bool, from: BlockRaw, to: BlockRaw, destProof: String, proof: String, stateProof: String) {
        self.toKeyBlock = toKeyBlock
        self.from = from
        self.to = to
        self.destProof = destProof
        self.proof = proof
        self.stateProof = stateProof
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case toKeyBlock = "to_key_block"
        case from
        case to
        case destProof = "dest_proof"
        case proof
        case stateProof = "state_proof"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(toKeyBlock, forKey: .toKeyBlock)
        try container.encode(from, forKey: .from)
        try container.encode(to, forKey: .to)
        try container.encode(destProof, forKey: .destProof)
        try container.encode(proof, forKey: .proof)
        try container.encode(stateProof, forKey: .stateProof)
    }
}

