//
// GetStakingPoolInfo200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetStakingPoolInfo200Response: Codable, JSONEncodable, Hashable {

    public var implementation: PoolImplementation
    public var pool: PoolInfo

    public init(implementation: PoolImplementation, pool: PoolInfo) {
        self.implementation = implementation
        self.pool = pool
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case implementation
        case pool
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(implementation, forKey: .implementation)
        try container.encode(pool, forKey: .pool)
    }
}

