//
// GetStorageProviders200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetStorageProviders200Response: Codable, JSONEncodable, Hashable {

    public var providers: [StorageProvider]

    public init(providers: [StorageProvider]) {
        self.providers = providers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case providers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(providers, forKey: .providers)
    }
}

