//
// GetStakingPools200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetStakingPools200Response: Codable, JSONEncodable, Hashable {

    public var pools: [PoolInfo]
    public var implementations: [String: PoolImplementation]

    public init(pools: [PoolInfo], implementations: [String: PoolImplementation]) {
        self.pools = pools
        self.implementations = implementations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pools
        case implementations
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pools, forKey: .pools)
        try container.encode(implementations, forKey: .implementations)
    }
}

