//
// GetWalletBackup200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetWalletBackup200Response: Codable, JSONEncodable, Hashable {

    public var dump: String

    public init(dump: String) {
        self.dump = dump
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dump
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(dump, forKey: .dump)
    }
}

