//
// GetWalletsByPublicKeyBulkRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetWalletsByPublicKeyBulkRequest: Codable, JSONEncodable, Hashable {

    public var publicKeys: [String]

    public init(publicKeys: [String]) {
        self.publicKeys = publicKeys
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publicKeys = "public_keys"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publicKeys, forKey: .publicKeys)
    }
}

