//
// ImagePreview.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ImagePreview: Codable, JSONEncodable, Hashable {

    public var resolution: String
    public var url: String

    public init(resolution: String, url: String) {
        self.resolution = resolution
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case resolution
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(resolution, forKey: .resolution)
        try container.encode(url, forKey: .url)
    }
}

