//
// InsufficientFunds.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Present on an error when a request failed because the source wallet does not hold enough TON to cover the required gas (error_code 50000).  */
public struct InsufficientFunds: Codable, JSONEncodable, Hashable {

    /** TON in nanotons required to cover transfer gas */
    public var _required: Int64
    /** TON in nanotons currently available on the source wallet */
    public var available: Int64

    public init(_required: Int64, available: Int64) {
        self._required = _required
        self.available = available
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _required = "required"
        case available
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(_required, forKey: ._required)
        try container.encode(available, forKey: .available)
    }
}

