//
// JettonQuantity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct JettonQuantity: Codable, JSONEncodable, Hashable {

    public var quantity: String
    public var walletAddress: AccountAddress
    public var jetton: JettonPreview

    public init(quantity: String, walletAddress: AccountAddress, jetton: JettonPreview) {
        self.quantity = quantity
        self.walletAddress = walletAddress
        self.jetton = jetton
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case quantity
        case walletAddress = "wallet_address"
        case jetton
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(quantity, forKey: .quantity)
        try container.encode(walletAddress, forKey: .walletAddress)
        try container.encode(jetton, forKey: .jetton)
    }
}

