//
// JettonMintAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct JettonMintAction: Codable, JSONEncodable, Hashable {

    public var recipient: AccountAddress
    public var recipientsWallet: String
    /** amount in quanta of tokens */
    public var amount: String
    public var jetton: JettonPreview

    public init(recipient: AccountAddress, recipientsWallet: String, amount: String, jetton: JettonPreview) {
        self.recipient = recipient
        self.recipientsWallet = recipientsWallet
        self.amount = amount
        self.jetton = jetton
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case recipient
        case recipientsWallet = "recipients_wallet"
        case amount
        case jetton
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(recipient, forKey: .recipient)
        try container.encode(recipientsWallet, forKey: .recipientsWallet)
        try container.encode(amount, forKey: .amount)
        try container.encode(jetton, forKey: .jetton)
    }
}

