//
// JettonAssetInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct JettonAssetInfo: Codable, JSONEncodable, Hashable {

    public var tokenType: DefiAssetAssetType
    public var defiProvider: DefiProvider

    public init(tokenType: DefiAssetAssetType, defiProvider: DefiProvider) {
        self.tokenType = tokenType
        self.defiProvider = defiProvider
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tokenType = "token_type"
        case defiProvider = "defi_provider"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tokenType, forKey: .tokenType)
        try container.encode(defiProvider, forKey: .defiProvider)
    }
}

