//
// JettonBalanceLock.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct JettonBalanceLock: Codable, JSONEncodable, Hashable {

    public var amount: String
    public var till: Int64

    public init(amount: String, till: Int64) {
        self.amount = amount
        self.till = till
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case till
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amount, forKey: .amount)
        try container.encode(till, forKey: .till)
    }
}

