//
// MessageConsequences.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Result of emulating a wallet message on the current blockchain state: describes the expected on-chain consequences (trace, high-level AccountEvent, risk) for the signing wallet. For UI display only.  */
public struct MessageConsequences: Codable, JSONEncodable, Hashable {

    public var trace: Trace
    public var risk: Risk
    public var event: AccountEvent

    public init(trace: Trace, risk: Risk, event: AccountEvent) {
        self.trace = trace
        self.risk = risk
        self.event = event
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case trace
        case risk
        case event
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(trace, forKey: .trace)
        try container.encode(risk, forKey: .risk)
        try container.encode(event, forKey: .event)
    }
}

