//
// Metadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Metadata: Codable, JSONEncodable, Hashable {

    public var encryptedBinary: String?

    public init(encryptedBinary: String? = nil) {
        self.encryptedBinary = encryptedBinary
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case encryptedBinary = "encrypted_binary"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(encryptedBinary, forKey: .encryptedBinary)
    }
}

