//
// Metadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Metadata: Codable, JSONEncodable, Hashable {

    /** hex encoded bytes */
    public var encryptedBinary: String
    /** hex encoded bytes */
    public var decryptionKey: String?

    public init(encryptedBinary: String, decryptionKey: String? = nil) {
        self.encryptedBinary = encryptedBinary
        self.decryptionKey = decryptionKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case encryptedBinary = "encrypted_binary"
        case decryptionKey = "decryption_key"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(encryptedBinary, forKey: .encryptedBinary)
        try container.encodeIfPresent(decryptionKey, forKey: .decryptionKey)
    }
}

