//
// MigrationPrepareRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MigrationPrepareRequest: Codable, JSONEncodable, Hashable {

    /** legacy source wallet to drain */
    public var from: String
    /** destination wallet TON address */
    public var to: String
    /** fiat currency for the preview values */
    public var currency: String? = "USD"

    public init(from: String, to: String, currency: String? = "USD") {
        self.from = from
        self.to = to
        self.currency = currency
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case from
        case to
        case currency
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(from, forKey: .from)
        try container.encode(to, forKey: .to)
        try container.encodeIfPresent(currency, forKey: .currency)
    }
}

