//
// MigrationPrepareResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MigrationPrepareResponse: Codable, JSONEncodable, Hashable {

    public var from: String
    public var to: String
    /** source wallet version (informational) */
    public var walletVersion: String
    /** ordered; sign and broadcast in array order, one entry per external message */
    public var transactions: [MigrationTransaction]

    public init(from: String, to: String, walletVersion: String, transactions: [MigrationTransaction]) {
        self.from = from
        self.to = to
        self.walletVersion = walletVersion
        self.transactions = transactions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case from
        case to
        case walletVersion = "wallet_version"
        case transactions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(from, forKey: .from)
        try container.encode(to, forKey: .to)
        try container.encode(walletVersion, forKey: .walletVersion)
        try container.encode(transactions, forKey: .transactions)
    }
}

