//
// MigrationTransaction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MigrationTransaction: Codable, JSONEncodable, Hashable {

    /** wallet seqno baked into the unsigned body */
    public var seqno: Int
    /** base64 BOC of the unsigned wallet body. Sign its hash, prepend the signature, wrap it in an external message and broadcast.  */
    public var boc: String
    /** base64 BOC of the wallet StateInit (code + data). Present only on the first transaction when the source wallet is not yet initialized  */
    public var stateInit: String?
    /** ordered raw internal messages carried by this transaction — the cells the wallet resends. These are what populate the payload/actions.  */
    public var messages: [MigrationOutMessage]
    public var emulation: MessageConsequences

    public init(seqno: Int, boc: String, stateInit: String? = nil, messages: [MigrationOutMessage], emulation: MessageConsequences) {
        self.seqno = seqno
        self.boc = boc
        self.stateInit = stateInit
        self.messages = messages
        self.emulation = emulation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case seqno
        case boc
        case stateInit = "state_init"
        case messages
        case emulation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(seqno, forKey: .seqno)
        try container.encode(boc, forKey: .boc)
        try container.encodeIfPresent(stateInit, forKey: .stateInit)
        try container.encode(messages, forKey: .messages)
        try container.encode(emulation, forKey: .emulation)
    }
}

