//
// ModelProtocol.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelProtocol: Codable, JSONEncodable, Hashable {

    public var name: String
    public var image: String?

    public init(name: String, image: String? = nil) {
        self.name = name
        self.image = image
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case image
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(image, forKey: .image)
    }
}

