//
// MultisigOrder.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MultisigOrder: Codable, JSONEncodable, Hashable {

    public var address: String
    public var orderSeqno: Int64
    public var threshold: Int
    public var sentForExecution: Bool
    public var signers: [String]
    public var approvalsNum: Int
    public var expirationDate: Int64
    public var risk: Risk
    public var creationDate: Int64
    public var signedBy: [String]
    public var multisigAddress: String
    public var changingParameters: MultisigOrderChangingParameters?

    public init(address: String, orderSeqno: Int64, threshold: Int, sentForExecution: Bool, signers: [String], approvalsNum: Int, expirationDate: Int64, risk: Risk, creationDate: Int64, signedBy: [String], multisigAddress: String, changingParameters: MultisigOrderChangingParameters? = nil) {
        self.address = address
        self.orderSeqno = orderSeqno
        self.threshold = threshold
        self.sentForExecution = sentForExecution
        self.signers = signers
        self.approvalsNum = approvalsNum
        self.expirationDate = expirationDate
        self.risk = risk
        self.creationDate = creationDate
        self.signedBy = signedBy
        self.multisigAddress = multisigAddress
        self.changingParameters = changingParameters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case orderSeqno = "order_seqno"
        case threshold
        case sentForExecution = "sent_for_execution"
        case signers
        case approvalsNum = "approvals_num"
        case expirationDate = "expiration_date"
        case risk
        case creationDate = "creation_date"
        case signedBy = "signed_by"
        case multisigAddress = "multisig_address"
        case changingParameters = "changing_parameters"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encode(orderSeqno, forKey: .orderSeqno)
        try container.encode(threshold, forKey: .threshold)
        try container.encode(sentForExecution, forKey: .sentForExecution)
        try container.encode(signers, forKey: .signers)
        try container.encode(approvalsNum, forKey: .approvalsNum)
        try container.encode(expirationDate, forKey: .expirationDate)
        try container.encode(risk, forKey: .risk)
        try container.encode(creationDate, forKey: .creationDate)
        try container.encode(signedBy, forKey: .signedBy)
        try container.encode(multisigAddress, forKey: .multisigAddress)
        try container.encodeIfPresent(changingParameters, forKey: .changingParameters)
    }
}

