//
// OracleRequestAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OracleRequestAction: Codable, JSONEncodable, Hashable {

    public var requester: AccountAddress
    public var responseTo: AccountAddress
    public var priceFeeds: [OraclePriceFeed]

    public init(requester: AccountAddress, responseTo: AccountAddress, priceFeeds: [OraclePriceFeed]) {
        self.requester = requester
        self.responseTo = responseTo
        self.priceFeeds = priceFeeds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case requester
        case responseTo = "response_to"
        case priceFeeds = "price_feeds"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requester, forKey: .requester)
        try container.encode(responseTo, forKey: .responseTo)
        try container.encode(priceFeeds, forKey: .priceFeeds)
    }
}

