//
// RawBlockchainConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RawBlockchainConfig: Codable, JSONEncodable, Hashable {

    public var config: [String: AnyCodable]

    public init(config: [String: AnyCodable]) {
        self.config = config
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case config
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(config, forKey: .config)
    }
}

