//
// Refund.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Refund: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case dnsPeriodTon = "DNS.ton"
        case dnsPeriodTg = "DNS.tg"
        case getGems = "GetGems"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var type: ModelType
    public var origin: String

    public init(type: ModelType, origin: String) {
        self.type = type
        self.origin = origin
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case origin
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(origin, forKey: .origin)
    }
}

