//
// RewardsStats.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RewardsStats: Codable, JSONEncodable, Hashable {

    /** Time series of APY values as [timestamp_ms, apy] pairs */
    public var apy: [[Double]]
    /** Time series of total stake in TON as [timestamp_ms, stake] pairs */
    public var totalStake: [[Double]]

    public init(apy: [[Double]], totalStake: [[Double]]) {
        self.apy = apy
        self.totalStake = totalStake
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case apy
        case totalStake = "total_stake"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(apy, forKey: .apy)
        try container.encode(totalStake, forKey: .totalStake)
    }
}

