//
// RoundInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RoundInfo: Codable, JSONEncodable, Hashable {

    public var startUtime: Int64?
    public var endUtime: Int64?
    /** Masterchain block seqno at (or nearest to) validation round start. */
    public var startBlock: Int
    /** Masterchain block seqno at (or nearest to) validation round end. */
    public var endBlock: Int

    public init(startUtime: Int64? = nil, endUtime: Int64? = nil, startBlock: Int, endBlock: Int) {
        self.startUtime = startUtime
        self.endUtime = endUtime
        self.startBlock = startBlock
        self.endBlock = endBlock
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case startUtime = "start_utime"
        case endUtime = "end_utime"
        case startBlock = "start_block"
        case endBlock = "end_block"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(startUtime, forKey: .startUtime)
        try container.encodeIfPresent(endUtime, forKey: .endUtime)
        try container.encode(startBlock, forKey: .startBlock)
        try container.encode(endBlock, forKey: .endBlock)
    }
}

