//
// ServiceStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceStatus: Codable, JSONEncodable, Hashable {

    public var restOnline: Bool = true
    public var indexingLatency: Int
    public var lastKnownMasterchainSeqno: Int

    public init(restOnline: Bool = true, indexingLatency: Int, lastKnownMasterchainSeqno: Int) {
        self.restOnline = restOnline
        self.indexingLatency = indexingLatency
        self.lastKnownMasterchainSeqno = lastKnownMasterchainSeqno
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case restOnline = "rest_online"
        case indexingLatency = "indexing_latency"
        case lastKnownMasterchainSeqno = "last_known_masterchain_seqno"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(restOnline, forKey: .restOnline)
        try container.encode(indexingLatency, forKey: .indexingLatency)
        try container.encode(lastKnownMasterchainSeqno, forKey: .lastKnownMasterchainSeqno)
    }
}

