//
// StateInit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StateInit: Codable, JSONEncodable, Hashable {

    public var boc: String
    public var interfaces: [String]

    public init(boc: String, interfaces: [String]) {
        self.boc = boc
        self.interfaces = interfaces
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case boc
        case interfaces
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(boc, forKey: .boc)
        try container.encode(interfaces, forKey: .interfaces)
    }
}

