//
// Subscriptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Subscriptions: Codable, JSONEncodable, Hashable {

    public var subscriptions: [Subscription]

    public init(subscriptions: [Subscription]) {
        self.subscriptions = subscriptions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case subscriptions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(subscriptions, forKey: .subscriptions)
    }
}

