//
// Transactions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Transactions: Codable, JSONEncodable, Hashable {

    public var transactions: [Transaction]

    public init(transactions: [Transaction]) {
        self.transactions = transactions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case transactions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(transactions, forKey: .transactions)
    }
}

