//
// ValidatorsSetListInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ValidatorsSetListInner: Codable, JSONEncodable, Hashable {

    public var publicKey: String
    public var weight: Int64
    public var adnlAddr: String?

    public init(publicKey: String, weight: Int64, adnlAddr: String? = nil) {
        self.publicKey = publicKey
        self.weight = weight
        self.adnlAddr = adnlAddr
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case publicKey = "public_key"
        case weight
        case adnlAddr = "adnl_addr"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(publicKey, forKey: .publicKey)
        try container.encode(weight, forKey: .weight)
        try container.encodeIfPresent(adnlAddr, forKey: .adnlAddr)
    }
}

