//
// ValueFlow.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ValueFlow: Codable, JSONEncodable, Hashable {

    public var account: AccountAddress
    /** this field will gone after Sept. 2026, use gram instead */
    @available(*, deprecated, message: "This property is deprecated.")
    public var ton: Int64?
    public var gram: Int64
    public var fees: Int64
    public var jettons: [ValueFlowJettonsInner]?

    public init(account: AccountAddress, ton: Int64? = nil, gram: Int64, fees: Int64, jettons: [ValueFlowJettonsInner]? = nil) {
        self.account = account
        self.ton = ton
        self.gram = gram
        self.fees = fees
        self.jettons = jettons
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case account
        case ton
        case gram
        case fees
        case jettons
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(account, forKey: .account)
        try container.encodeIfPresent(ton, forKey: .ton)
        try container.encode(gram, forKey: .gram)
        try container.encode(fees, forKey: .fees)
        try container.encodeIfPresent(jettons, forKey: .jettons)
    }
}

