//
// VaultDepositInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct VaultDepositInfo: Codable, JSONEncodable, Hashable {

    public var price: Price
    public var vault: String

    public init(price: Price, vault: String) {
        self.price = price
        self.vault = vault
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case price
        case vault
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(price, forKey: .price)
        try container.encode(vault, forKey: .vault)
    }
}

