//
// WalletDNS.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WalletDNS: Codable, JSONEncodable, Hashable {

    public var address: String
    public var account: AccountAddress
    public var isWallet: Bool
    public var hasMethodPubkey: Bool
    public var hasMethodSeqno: Bool
    public var names: [String]

    public init(address: String, account: AccountAddress, isWallet: Bool, hasMethodPubkey: Bool, hasMethodSeqno: Bool, names: [String]) {
        self.address = address
        self.account = account
        self.isWallet = isWallet
        self.hasMethodPubkey = hasMethodPubkey
        self.hasMethodSeqno = hasMethodSeqno
        self.names = names
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case account
        case isWallet = "is_wallet"
        case hasMethodPubkey = "has_method_pubkey"
        case hasMethodSeqno = "has_method_seqno"
        case names
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encode(account, forKey: .account)
        try container.encode(isWallet, forKey: .isWallet)
        try container.encode(hasMethodPubkey, forKey: .hasMethodPubkey)
        try container.encode(hasMethodSeqno, forKey: .hasMethodSeqno)
        try container.encode(names, forKey: .names)
    }
}

