//
// WithdrawStakeRequestAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** validator&#39;s participation in elections */
public struct WithdrawStakeRequestAction: Codable, JSONEncodable, Hashable {

    public var amount: Int64?
    public var staker: AccountAddress
    public var pool: AccountAddress
    public var implementation: PoolImplementationType
    public var stakeMeta: Price?

    public init(amount: Int64? = nil, staker: AccountAddress, pool: AccountAddress, implementation: PoolImplementationType, stakeMeta: Price? = nil) {
        self.amount = amount
        self.staker = staker
        self.pool = pool
        self.implementation = implementation
        self.stakeMeta = stakeMeta
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case staker
        case pool
        case implementation
        case stakeMeta = "stake_meta"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encode(staker, forKey: .staker)
        try container.encode(pool, forKey: .pool)
        try container.encode(implementation, forKey: .implementation)
        try container.encodeIfPresent(stakeMeta, forKey: .stakeMeta)
    }
}

