//
// WithdrawTokenStakeRequestAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WithdrawTokenStakeRequestAction: Codable, JSONEncodable, Hashable {

    public var staker: AccountAddress
    public var _protocol: ModelProtocol
    public var stakeMeta: Price?

    public init(staker: AccountAddress, _protocol: ModelProtocol, stakeMeta: Price? = nil) {
        self.staker = staker
        self._protocol = _protocol
        self.stakeMeta = stakeMeta
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case staker
        case _protocol = "protocol"
        case stakeMeta = "stake_meta"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(staker, forKey: .staker)
        try container.encode(_protocol, forKey: ._protocol)
        try container.encodeIfPresent(stakeMeta, forKey: .stakeMeta)
    }
}

