//
// AccountStateNotification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Account state after a confirmed or finalized transaction on a subscribed address. */
public struct AccountStateNotification: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case accountStateChange = "account_state_change"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var type: ModelType
    public var finality: NonPendingFinality
    /** TON account or contract address in any valid format accepted by Toncenter. */
    public var account: String
    /** Account state similar to Toncenter API v3 AccountState, without full code and data BoCs according to the source document.  */
    public var state: [String: AnyCodable]

    public init(type: ModelType, finality: NonPendingFinality, account: String, state: [String: AnyCodable]) {
        self.type = type
        self.finality = finality
        self.account = account
        self.state = state
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case finality
        case account
        case state
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(finality, forKey: .finality)
        try container.encode(account, forKey: .account)
        try container.encode(state, forKey: .state)
    }
}

