//
// JettonsNotification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Jetton wallet snapshot for a wallet or owner related to a subscribed address. */
public struct JettonsNotification: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case jettonsChange = "jettons_change"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var type: ModelType
    public var finality: NonPendingFinality
    /** Opaque Toncenter API v3 JettonWallet object. */
    public var jetton: [String: AnyCodable]
    /** Mapping of addresses to friendly-address and TON DNS information. */
    public var addressBook: [String: AnyCodable]?
    /** Mapping of token-related addresses to metadata objects. */
    public var metadata: [String: AnyCodable]?

    public init(type: ModelType, finality: NonPendingFinality, jetton: [String: AnyCodable], addressBook: [String: AnyCodable]? = nil, metadata: [String: AnyCodable]? = nil) {
        self.type = type
        self.finality = finality
        self.jetton = jetton
        self.addressBook = addressBook
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case finality
        case jetton
        case addressBook = "address_book"
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(finality, forKey: .finality)
        try container.encode(jetton, forKey: .jetton)
        try container.encodeIfPresent(addressBook, forKey: .addressBook)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}

