//
// SseSubscriptionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** SSE subscription parameters.  Rules from the source document: - &#x60;types&#x60; is required. - If subscribing to &#x60;trace&#x60;, &#x60;trace_external_hash_norms&#x60; is required. - If subscribing to any non-&#x60;trace&#x60; event type, &#x60;addresses&#x60; is required. - &#x60;supported_action_types&#x60; defaults to &#x60;[\&quot;latest\&quot;]&#x60; on the server side.  */
public struct SseSubscriptionRequest: Codable, JSONEncodable, Hashable {

    /** Wallet or contract addresses to monitor. */
    public var addresses: [String]?
    /** Trace external hashes to monitor. */
    public var traceExternalHashNorms: [String]?
    /** Event types to receive. */
    public var types: Set<SubscriptionType>
    public var minFinality: Finality?
    /** Include friendly names and TON DNS information for known addresses. */
    public var includeAddressBook: Bool?
    /** Include metadata for known token contracts such as Jettons and NFTs. */
    public var includeMetadata: Bool?
    /** Filter delivered actions by action classification type. Applies only to `actions` events.  */
    public var actionTypes: [String]?
    /** Advertises which action classification versions the client understands. */
    public var supportedActionTypes: [String]?

    public init(addresses: [String]? = nil, traceExternalHashNorms: [String]? = nil, types: Set<SubscriptionType>, minFinality: Finality? = nil, includeAddressBook: Bool? = nil, includeMetadata: Bool? = nil, actionTypes: [String]? = nil, supportedActionTypes: [String]? = nil) {
        self.addresses = addresses
        self.traceExternalHashNorms = traceExternalHashNorms
        self.types = types
        self.minFinality = minFinality
        self.includeAddressBook = includeAddressBook
        self.includeMetadata = includeMetadata
        self.actionTypes = actionTypes
        self.supportedActionTypes = supportedActionTypes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case addresses
        case traceExternalHashNorms = "trace_external_hash_norms"
        case types
        case minFinality = "min_finality"
        case includeAddressBook = "include_address_book"
        case includeMetadata = "include_metadata"
        case actionTypes = "action_types"
        case supportedActionTypes = "supported_action_types"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(addresses, forKey: .addresses)
        try container.encodeIfPresent(traceExternalHashNorms, forKey: .traceExternalHashNorms)
        try container.encode(types, forKey: .types)
        try container.encodeIfPresent(minFinality, forKey: .minFinality)
        try container.encodeIfPresent(includeAddressBook, forKey: .includeAddressBook)
        try container.encodeIfPresent(includeMetadata, forKey: .includeMetadata)
        try container.encodeIfPresent(actionTypes, forKey: .actionTypes)
        try container.encodeIfPresent(supportedActionTypes, forKey: .supportedActionTypes)
    }
}

