//
// SubscriptionType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Event type that can be requested in a subscription. */
public enum SubscriptionType: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case transactions = "transactions"
    case actions = "actions"
    case trace = "trace"
    case accountStateChange = "account_state_change"
    case jettonsChange = "jettons_change"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
