//
// TransactionsNotification.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Trace-scoped transaction snapshot, ordered by LT descending. */
public struct TransactionsNotification: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case transactions = "transactions"
        case unknownDefaultOpenApi = "unknown_default_open_api"
    }
    public var type: ModelType
    public var finality: Finality
    /** Normalized hash of the external message that initiated a trace. */
    public var traceExternalHashNorm: String
    public var transactions: [[String: AnyCodable]]
    /** Mapping of addresses to friendly-address and TON DNS information. */
    public var addressBook: [String: AnyCodable]?
    /** Mapping of token-related addresses to metadata objects. */
    public var metadata: [String: AnyCodable]?

    public init(type: ModelType, finality: Finality, traceExternalHashNorm: String, transactions: [[String: AnyCodable]], addressBook: [String: AnyCodable]? = nil, metadata: [String: AnyCodable]? = nil) {
        self.type = type
        self.finality = finality
        self.traceExternalHashNorm = traceExternalHashNorm
        self.transactions = transactions
        self.addressBook = addressBook
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case finality
        case traceExternalHashNorm = "trace_external_hash_norm"
        case transactions
        case addressBook = "address_book"
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(finality, forKey: .finality)
        try container.encode(traceExternalHashNorm, forKey: .traceExternalHashNorm)
        try container.encode(transactions, forKey: .transactions)
        try container.encodeIfPresent(addressBook, forKey: .addressBook)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}

